### ISSUE TITLE
Snake moves way too sloooooooooow

### ISSUE THREAD

**Issue by Danct12** [wick3dr0se/snake#6] opened 2023-05-11 12:06 UTC
Bash version: 5.1.16

Snake seems to move very slow, around two seconds per frame it seems.

**Comment by wick3dr0se** [comment] 2023-05-11 14:06
Seems it got a lot of complaints about initial speed lmao! It's set to 1 second at first and drops .1 second per block eaten. I suppose I can start the speed around .75 or quicker and go from there. My testing was done on with an extremely small floating window and from my phone

**Comment by wick3dr0se** [comment] 2023-05-11 18:37
@Danct12 I completely changed how the speeds were setup. It starts at .7 second delay now and then gradually reduces less as speeds increase. So now the final speed isn't so insane as well

Closing because the issue is solved and speeds are better defined

**Closed as completed** 2023-05-12 19:06 UTC
